// Copyright (c) 2022- Burak Kara, MIT License
// See LICENSE file in the project root for full license information.

using CrossCloudKit.Interfaces.Enums;

namespace CrossCloudKit.Interfaces.Records;

/// <summary>
/// The result of a non-streaming LLM chat completion.
/// </summary>
/// <example>
/// <code>
/// var result = await llmService.CompleteAsync(request);
/// if (result.IsSuccessful)
/// {
///     Console.WriteLine(result.Data.Content);
///     if (result.Data.FinishReason == LLMFinishReason.ToolCall)
///         foreach (var tc in result.Data.ToolCalls!)
///             Console.WriteLine($"Call {tc.Name}({tc.Arguments})");
/// }
/// </code>
/// </example>
public sealed record LLMResponse
{
    /// <summary>The text content generated by the model.</summary>
    public string Content { get; init; } = string.Empty;

    /// <summary>The reason generation stopped.</summary>
    public LLMFinishReason FinishReason { get; init; }

    /// <summary>Token usage statistics, if provided by the backend.</summary>
    public LLMUsage? Usage { get; init; }

    /// <summary>
    /// Tool calls requested by the model.
    /// Non-empty only when <see cref="FinishReason"/> is <see cref="LLMFinishReason.ToolCall"/>.
    /// </summary>
    public IReadOnlyList<LLMToolCall>? ToolCalls { get; init; }
}
