// Copyright (c) 2022- Burak Kara, MIT License
// See LICENSE file in the project root for full license information.

namespace CrossCloudKit.Interfaces.Enums;

/// <summary>
/// Specifies the role of a participant in an LLM conversation.
/// </summary>
public enum LLMRole
{
    /// <summary>A system-level instruction that sets the assistant's behaviour.</summary>
    System,

    /// <summary>A message authored by the human user.</summary>
    User,

    /// <summary>A message generated by the AI assistant.</summary>
    Assistant,

    /// <summary>A message representing the result of a tool invocation.</summary>
    Tool
}
